"use client";
import { useEffect, useRef, useState } from "react";
const tracks = Array.from({ length: 12 }, (_, index) => `/music/dodam-${index + 1}.mp3`); const fadeSeconds = 6;
export default function MusicPlayer() {
  const [playing, setPlaying] = useState(false); const [open, setOpen] = useState(false); const [volume, setVolume] = useState(.18); const [voiceVolume, setVoiceVolume] = useState(100);
  const playersRef = useRef<HTMLAudioElement[]>([]); const activeRef = useRef(0); const trackRef = useRef(0); const fadingRef = useRef(false); const frameRef = useRef<number | null>(null);
  useEffect(() => { const savedVoice = Number(localStorage.getItem("dodam_voice_volume")); if (Number.isFinite(savedVoice) && savedVoice >= 0) setVoiceVolume(savedVoice); void fetch("/api/settings/music").then(r => r.json()).then((d: { volume?: number }) => { const saved = Number(localStorage.getItem("dodam_music_volume")); setVolume(Number.isFinite(saved) && saved >= 0 ? saved / 100 : Math.min(Math.max((d.volume ?? 18) / 100, 0), 1)); }).catch(() => undefined); }, []);
  useEffect(() => { playersRef.current.forEach((audio, index) => { if (!fadingRef.current || index === activeRef.current) audio.volume = volume; }); }, [volume]);
  useEffect(() => () => { playersRef.current.forEach(a => a.pause()); if (frameRef.current) cancelAnimationFrame(frameRef.current); }, []);
  function ensurePlayers() { if (!playersRef.current.length) { playersRef.current = [new Audio(tracks[0]), new Audio(tracks[1])]; playersRef.current.forEach(a => a.preload = "auto"); } return playersRef.current; }
  function watch() { const current = playersRef.current[activeRef.current]; if (current && Number.isFinite(current.duration) && current.duration - current.currentTime <= fadeSeconds && !fadingRef.current) void crossfade(); if (!current?.paused) frameRef.current = requestAnimationFrame(watch); }
  async function crossfade() { fadingRef.current = true; const oldIndex = activeRef.current; const nextIndex = oldIndex ? 0 : 1; trackRef.current = (trackRef.current + 1) % tracks.length; const next = playersRef.current[nextIndex]; const old = playersRef.current[oldIndex]; next.src = tracks[trackRef.current]; next.currentTime = 0; next.volume = 0; try { await next.play(); } catch { fadingRef.current = false; return; } const started = performance.now(); const fade = () => { const p = Math.min((performance.now() - started) / (fadeSeconds * 1000), 1); old.volume = volume * (1 - p); next.volume = volume * p; if (p < 1) requestAnimationFrame(fade); else { old.pause(); old.currentTime = 0; activeRef.current = nextIndex; fadingRef.current = false; } }; requestAnimationFrame(fade); }
  async function toggle() { const players = ensurePlayers(); if (playing) { players.forEach(a => a.pause()); if (frameRef.current) cancelAnimationFrame(frameRef.current); setPlaying(false); return; } const active = players[activeRef.current]; active.src = tracks[trackRef.current]; active.volume = volume; try { await active.play(); setPlaying(true); frameRef.current = requestAnimationFrame(watch); } catch { setPlaying(false); } }
  function changeMusic(value: number) { setVolume(value / 100); localStorage.setItem("dodam_music_volume", String(value)); }
  function changeVoice(value: number) { setVoiceVolume(value); localStorage.setItem("dodam_voice_volume", String(value)); }
  return <div className="sound-settings"><button className="settings-button" type="button" onClick={() => setOpen(v => !v)} aria-expanded={open} aria-label="음량 설정">⚙ 설정</button>{open && <section className="sound-panel"><strong>음량</strong><label><span>배경음 <b>{Math.round(volume * 100)}%</b></span><input type="range" min="0" max="50" value={Math.round(volume * 100)} onChange={e => changeMusic(Number(e.target.value))} /></label><label><span>목소리 <b>{voiceVolume}%</b></span><input type="range" min="0" max="100" value={voiceVolume} onChange={e => changeVoice(Number(e.target.value))} /></label><button className="music-switch" type="button" onClick={() => void toggle()}>{playing ? "♫ 배경음 끄기" : "♪ 배경음 켜기"}</button></section>}</div>;
}
